# Generated by Django 5.1.4 on 2025-01-27 13:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelinePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the timeline')),
                ('timeline_entries', wagtail.fields.StreamField([('timeline_entry', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the date or time period', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the title of this timeline entry', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Enter the description of this timeline entry', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional: Choose an image to accompany this entry', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('date', 0), ('title', 1), ('description', 2), ('image', 3)]], {})}, help_text='Add timeline entries here')),
            ],
            options={
                'verbose_name': 'Timeline Page',
                'verbose_name_plural': 'Timeline Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
