# Generated by Django 5.1.4 on 2025-01-21 16:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_site_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 5), ('features_grid', 11), ('cta', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main hero heading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Hero description'}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('text', 1), ('primary_button_text', 2), ('primary_button_url', 3), ('secondary_button_text', 2), ('secondary_button_url', 3), ('image', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 9: ('wagtail.blocks.StructBlock', [[('icon', 4), ('title', 7), ('text', 8), ('button_text', 2), ('button_url', 3)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 2), ('intro_text', 6), ('features', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 7), ('text', 8), ('primary_button_text', 2), ('primary_button_url', 3), ('secondary_button_text', 2), ('secondary_button_url', 3), ('image', 4)]], {})}),
        ),
    ]
