# Generated by Django 5.1.4 on 2025-01-21 16:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_hero_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 6), ('features_grid', 12), ('cta', 13)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('split', 'Split Content'), ('background', 'Background Image')], 'help_text': 'Choose the hero section style'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main hero heading'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Hero description'}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.images.blocks.ImageBlock', [], {}), 6: ('wagtail.blocks.StructBlock', [[('style', 0), ('heading', 1), ('text', 2), ('primary_button_text', 3), ('primary_button_url', 4), ('secondary_button_text', 3), ('secondary_button_url', 4), ('image', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 10: ('wagtail.blocks.StructBlock', [[('icon', 5), ('title', 8), ('text', 9), ('button_text', 3), ('button_url', 4)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 3), ('intro_text', 7), ('features', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 8), ('text', 9), ('primary_button_text', 3), ('primary_button_url', 4), ('secondary_button_text', 3), ('secondary_button_url', 4), ('image', 5)]], {})}),
        ),
    ]
