# Generated by Django 5.1.4 on 2025-01-28 10:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 9), ('features_grid', 17), ('cta', 18)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('split', 'Split Content'), ('background', 'Background Image')], 'help_text': 'Choose the hero section style'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main hero heading'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Hero description'}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal page link for primary button', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL for primary button', 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal page link for secondary button', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL for secondary button', 'required': False}), 8: ('wagtail.images.blocks.ImageBlock', [], {}), 9: ('wagtail.blocks.StructBlock', [[('style', 0), ('heading', 1), ('text', 2), ('primary_button_text', 3), ('primary_button_page', 4), ('primary_button_url', 5), ('secondary_button_text', 3), ('secondary_button_page', 6), ('secondary_button_url', 7), ('image', 8)]], {}), 10: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 11: ('wagtail.blocks.CharBlock', (), {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 13: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal page link', 'required': False}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('icon', 8), ('title', 11), ('text', 12), ('button_text', 3), ('button_page', 13), ('button_url', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('title', 3), ('intro_text', 10), ('features', 16)]], {}), 18: ('wagtail.blocks.StructBlock', [[('heading', 11), ('text', 12), ('primary_button_text', 3), ('primary_button_page', 4), ('primary_button_url', 5), ('secondary_button_text', 3), ('secondary_button_page', 6), ('secondary_button_url', 7), ('image', 8)]], {})}),
        ),
    ]
