# Generated by Django 5.1.4 on 2025-01-18 16:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfoliopage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='sub_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
