# Generated by Django 5.1.4 on 2025-01-21 16:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliopage_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('embed_block', 7), ('card', 18), ('featured_posts', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media'}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional tag displayed at the top of the card', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading of the card'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional secondary heading', 'required': False}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Main content text'}), 12: ('wagtail.images.blocks.ImageBlock', [], {'help_text': 'Optional image to display alongside content'}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')], 'help_text': 'Choose which side the image appears on'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text for the primary green button', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link for the primary button', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text for the secondary pink button', 'required': False}), 17: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link for the secondary button', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('card_tag', 8), ('heading', 9), ('sub_heading', 10), ('text', 11), ('image', 12), ('image_position', 13), ('primary_button_text', 14), ('primary_button_url', 15), ('secondary_button_text', 16), ('secondary_button_url', 17)]], {'group': 'Sections'}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section heading'}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Optional introduction text', 'required': False}), 21: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPage']}), 22: ('wagtail.blocks.ListBlock', (21,), {'help_text': 'Select blog posts to feature'}), 23: ('wagtail.blocks.StructBlock', [[('heading', 19), ('text', 20), ('posts', 22)]], {'group': 'Sections'})}, help_text='Use this section to list your projects and skills.'),
        ),
    ]
