# Generated by Django 5.1.4 on 2025-01-17 22:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_formpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='title_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
