# Generated by Django 5.1.4 on 2025-01-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_formpage_title_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formpage',
            old_name='title_text',
            new_name='large_text',
        ),
    ]
