# Generated by Django 5.1.4 on 2025-01-22 16:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_footerconfiguration_headerconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerconfiguration',
            name='footer_logo',
        ),
        migrations.RemoveField(
            model_name='footerconfiguration',
            name='privacy_text',
        ),
        migrations.RemoveField(
            model_name='footerconfiguration',
            name='subscribe_button_text',
        ),
        migrations.RemoveField(
            model_name='footerconfiguration',
            name='subscribe_description',
        ),
        migrations.RemoveField(
            model_name='footerconfiguration',
            name='subscribe_title',
        ),
        migrations.AddField(
            model_name='footerconfiguration',
            name='content',
            field=wagtail.fields.StreamField([('column', 5), ('social_links', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: add an SVG icon code', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 1), ('icon', 2)]], {}), 4: ('wagtail.blocks.StreamBlock', [[('link', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('links', 4)]], {})}, verbose_name='Footer Content'),
        ),
        migrations.AddField(
            model_name='footerconfiguration',
            name='privacy_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='footerconfiguration',
            name='social_links',
            field=wagtail.fields.StreamField([('social_link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: add an SVG icon code', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 1), ('icon', 2)]], {})}, verbose_name='Social Links'),
        ),
        migrations.AddField(
            model_name='footerconfiguration',
            name='terms_link',
            field=models.URLField(blank=True),
        ),
    ]
