# Generated by Django 5.1.4 on 2025-01-22 16:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_footerconfiguration_footer_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerconfiguration',
            name='content',
            field=wagtail.fields.StreamField([('column', 7), ('social_links', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Internal Page'), ('external', 'External URL')]}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: add an SVG icon code', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_type', 1), ('page', 2), ('external_url', 3), ('icon', 4)]], {}), 6: ('wagtail.blocks.StreamBlock', [[('link', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('links', 6)]], {})}, verbose_name='Footer Content'),
        ),
        migrations.AlterField(
            model_name='footerconfiguration',
            name='social_links',
            field=wagtail.fields.StreamField([('social_link', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('page', 'Internal Page'), ('external', 'External URL')]}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: add an SVG icon code', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('link_type', 1), ('page', 2), ('external_url', 3), ('icon', 4)]], {})}, verbose_name='Social Links'),
        ),
    ]
