# Generated by Django 5.1.4 on 2025-01-28 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_sitelogo'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerconfiguration',
            name='contact_button_link',
        ),
        migrations.RemoveField(
            model_name='headerconfiguration',
            name='cv_button_link',
        ),
        migrations.AddField(
            model_name='headerconfiguration',
            name='contact_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Contact Page'),
        ),
        migrations.AddField(
            model_name='headerconfiguration',
            name='cv_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='CV Page'),
        ),
    ]
