# Generated by Django 5.1.4 on 2025-01-31 14:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_headerconfiguration_contact_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='contact_info',
            field=wagtail.fields.StreamField([('contact_item', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'SVG path data for the icon', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.URLBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('icon_svg', 0), ('title', 1), ('description', 1), ('link_text', 1), ('link_url', 2)]], {})}),
        ),
    ]
