# Generated by Django 5.1.4 on 2025-07-17 14:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_formpage_contact_info'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='contact_info',
            field=wagtail.fields.StreamField([('contact_item', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'SVG path data for the icon', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('social', 'Social Media Link'), ('email', 'Email Link')]}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.EmailBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('icon_svg', 0), ('title', 1), ('description', 1), ('contact_type', 2), ('social_link', 3), ('email', 4)]], {})}),
        ),
        migrations.CreateModel(
            name='SiteFavicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Site Favicon',
                'verbose_name_plural': 'Site Favicon',
            },
        ),
    ]
