# Generated by Django 5.1.4 on 2025-01-28 10:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(help_text='Brief introduction or professional summary')),
                ('cv_file', wagtail.fields.StreamField([('document', 0)], block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload your CV document'})})),
                ('experience', wagtail.fields.StreamField([('experience', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.DateBlock', (), {}), 2: ('wagtail.blocks.DateBlock', (), {'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 4: ('wagtail.blocks.StructBlock', [[('company', 0), ('position', 0), ('date_from', 1), ('date_to', 2), ('description', 3)]], {})})),
                ('education', wagtail.fields.StreamField([('education', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.DateBlock', (), {}), 2: ('wagtail.blocks.DateBlock', (), {'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 4: ('wagtail.blocks.StructBlock', [[('institution', 0), ('degree', 0), ('date_from', 1), ('date_to', 2), ('description', 3)]], {})})),
                ('skills', wagtail.fields.StreamField([('skill_group', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.StructBlock', [[('category', 0), ('skills', 1)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
